robot1:
  kintrol_server:
    command_topic: "/robot1_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    control_freq: 250
    joint_model_group: "rob1_planning_group"

    ros_queue_size: 2

robot2:
  kintrol_server:
    command_topic: "/robot2_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    control_freq: 250
    joint_model_group: "rob2_planning_group"

    ros_queue_size: 2

robot3:
  kintrol_server:
    command_topic: "/robot3_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    control_freq: 250
    joint_model_group: "rob3_planning_group"

    ros_queue_size: 2