robot1:
  kintrol_server:
    command_topic: "/robot1_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "rob1_planning_group"
    end_effector: "rob1_typhoon_extruder"
    pose_frame: "positioner"
    control_freq: 250
    prop_gain: 0.1
    ros_queue_size: 2
    
    positioner_joint_model_group: "positioner_planning_group"
    positioner_command_topic: "/positioner_joint_velocity_controller/command"

robot2:
  kintrol_server:
    command_topic: "/robot2_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "rob2_planning_group"
    end_effector: "rob2_typhoon_extruder"
    pose_frame: "positioner"
    control_freq: 250
    prop_gain: 0.1
    ros_queue_size: 2

    positioner_joint_model_group: "positioner_planning_group"
    positioner_command_topic: "/positioner_joint_velocity_controller/command"

robot3:
  kintrol_server:
    command_topic: "/robot3_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "rob3_planning_group"
    end_effector: "rob3_typhoon_extruder"
    pose_frame: "positioner"
    control_freq: 250
    prop_gain: 0.1
    ros_queue_size: 2

    positioner_joint_model_group: "positioner_planning_group"
    positioner_command_topic: "/positioner_joint_velocity_controller/command"
