robot1:
  kintrol_server:
    command_topic: "/robot1_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "rob1_planning_group"
    end_effector: "rob1_typhoon_extruder"
    control_freq: 250
    prop_gain: 0.1
    ros_queue_size: 2

    kintroller_names: ["kintroller", "coordinated_kintroller"]

    kintroller:
      pose_frame: "positioner_static"
      kintroller_type: 0 # 0: kintroller, 1: coordinated controller

    coordinated_kintroller:
      kintroller_type: 1 # 0: kintroller, 1: coordinated controller
      pose_frame: "positioner"
      positioner_joint_model_group: "positioner_planning_group"
      positioner_command_topic: "/positioner_joint_velocity_controller/command"
      constant_orient: true



robot2:
  kintrol_server:
    command_topic: "/robot2_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "rob2_planning_group"
    end_effector: "rob2_typhoon_extruder"
    control_freq: 250
    prop_gain: 0.1
    ros_queue_size: 2

    kintroller_names: ["kintroller", "coordinated_kintroller"]

    kintroller:
      pose_frame: "positioner_static"
      kintroller_type: 0 # 0: kintroller, 1: coordinated controller

    coordinated_kintroller:
      kintroller_type: 1 # 0: kintroller, 1: coordinated controller
      pose_frame: "positioner"
      positioner_joint_model_group: "positioner_planning_group"
      positioner_command_topic: "/positioner_joint_velocity_controller/command"
      constant_orient: true

robot3:
  kintrol_server:
    command_topic: "/robot3_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "rob3_planning_group"
    end_effector: "rob3_typhoon_extruder"
    control_freq: 250
    prop_gain: 0.1
    ros_queue_size: 2

    kintroller_names: ["kintroller", "coordinated_kintroller"]

    kintroller:
      pose_frame: "positioner_static"
      kintroller_type: 0 # 0: kintroller, 1: coordinated controller

    coordinated_kintroller:
      kintroller_type: 1 # 0: kintroller, 1: coordinated controller
      pose_frame: "positioner"
      positioner_joint_model_group: "positioner_planning_group"
      positioner_command_topic: "/positioner_joint_velocity_controller/command"
      constant_orient: true

positioner:
  kintrol_server:
    command_topic: "/positioner_joint_velocity_controller/command"
    setpoint_topic: "setpoint"
    joint_model_group: "positioner_planning_group"
    end_effector: "positioner"
    control_freq: 100
    prop_gain: 0.1
    ros_queue_size: 2

    kintroller_names: ["positioner_kintroller"]

    positioner_kintroller:
      kintroller_type: 2 # 2: positioner controller
      pose_frame: "world"
      coord_group_names: ["robot1", "robot2", "robot3"]